const path = require("path");

module.exports = {
  stories: [
    "../stories/**/*.stories.@(js|jsx|ts|tsx|mdx)",
    "../../../packages/app/**/*.stories.@(js|jsx|ts|tsx|mdx)",
    "../../../packages/design-system/**/*.stories.@(js|jsx|ts|tsx|mdx)",
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "storybook-addon-next",
    {
      name: "@storybook/addon-react-native-web",
      options: {
        modulesToTranspile: [
          "@gorhom/bottom-sheet",
          "@gorhom/portal",
          "twrnc",
          "moti",
          "@motify/components",
          "@motify/core",
          "expo-next-react-navigation",
          "@zeego/menu",
          "@zeego/dropdown-menu",
          "react-native-reanimated",
          "@react-navigation/native",
          "expo-linear-gradient",
          "@showtime-xyz/universal.typography",
          "@showtime-xyz/universal.tailwind",
          "@showtime-xyz/universal.view",
          "@showtime-xyz/universal.text",
          "@showtime-xyz/universal.accordion",
          "@showtime-xyz/universal.activity-indicator",
          "@showtime-xyz/universal.alert",
          "@showtime-xyz/universal.avatar",
          "@showtime-xyz/universal.bottom-sheet",
          "@showtime-xyz/universal.button",
          "@showtime-xyz/universal.checkbox",
          "@showtime-xyz/universal.country-code-picker",
          "@showtime-xyz/universal.data-pill",
          "@showtime-xyz/universal.divider",
          "@showtime-xyz/universal.fieldset",
          "@showtime-xyz/universal.hooks",
          "@showtime-xyz/universal.icon",
          "@showtime-xyz/universal.image",
          "@showtime-xyz/universal.input",
          "@showtime-xyz/universal.label",
          "@showtime-xyz/universal.light-box",
          "@showtime-xyz/universal.modal",
          "@showtime-xyz/universal.modal-screen",
          "@showtime-xyz/universal.modal-sheet",
          "@showtime-xyz/universal.pinch-to-zoom",
          "@showtime-xyz/universal.pressable",
          "@showtime-xyz/universal.pressable-scale",
          "@showtime-xyz/universal.router",
          "@showtime-xyz/universal.safe-area",
          "@showtime-xyz/universal.scroll-view",
          "@showtime-xyz/universal.segmented-control",
          "@showtime-xyz/universal.select",
          "@showtime-xyz/universal.skeleton",
          "@showtime-xyz/universal.snackbar",
          "@showtime-xyz/universal.spinner",
          "@showtime-xyz/universal.switch",
          "@showtime-xyz/universal.text-input",
          "@showtime-xyz/universal.toast",
          "@showtime-xyz/universal.tooltip",
          "@showtime-xyz/universal.verification-badge",
        ],
        babelPlugins: ["react-native-reanimated/plugin"],
      },
    },
  ],
  core: {
    builder: "webpack5",
  },
  typescript: { reactDocgen: false },
  webpackFinal: async (config, { configType }) => {
    config.resolve.fallback = {
      stream: require.resolve("stream-browserify"),
      crypto: require.resolve("crypto-browserify"),
    };
    return config;
  },
};
