const MAX_CONTENT_WIDTH = 1140;
const MAX_COVER_WIDTH = 1330;
const MAX_HEADER_WIDTH = 1440;
const MOBILE_WEB_TABS_HEIGHT = 50;
const WEB_HEADER_HEIGHT = 64;
const MOBILE_WEB_HEADER_HEIGHT = 50;

export {
  MAX_CONTENT_WIDTH,
  MAX_HEADER_WIDTH,
  MAX_COVER_WIDTH,
  MOBILE_WEB_TABS_HEIGHT,
  WEB_HEADER_HEIGHT,
  MOBILE_WEB_HEADER_HEIGHT,
};
