const MAX_CONTENT_WIDTH = 1140;
const MAX_COVER_WIDTH = 1330;
const MAX_HEADER_WIDTH = 1440;
const MOBILE_WEB_TABS_HEIGHT = 50;
const MOBILE_WEB_BOTTOM_NAV_HEIGHT = 64;

export {
  MAX_CONTENT_WIDTH,
  MAX_HEADER_WIDTH,
  MAX_COVER_WIDTH,
  MOBILE_WEB_TABS_HEIGHT,
  MOBILE_WEB_BOTTOM_NAV_HEIGHT,
};
