# This is a basic workflow to help you get started with Actions
name: Upload build to Waldo

defaults:
  run:
    working-directory: apps/expo

# Controls when the workflow will run
on:
  # Triggers the workflow on push/merge request events but only for the "staging" branch
  push:
    branches: ["staging"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install --immutable

      - name: Expo prebuild
        run: yarn waldo:build

      - name: Build with Xcode
        run: |
          DERIVED_DATA_PATH=/tmp/Showtime-$(uuidgen)

          cd ios/ && E2E=true FLIPPER_DISABLE=1 STAGE=development xcodebuild -workspace Showtime.xcworkspace    \
                     -scheme Showtime                              \
                     -configuration Release                        \
                     -sdk iphonesimulator                          \
                     ARCHS=x86_64 ONLY_ACTIVE_ARCH=NO              \
                     -derivedDataPath "$DERIVED_DATA_PATH"         \
                     clean build

          echo "APP_DIR_PATH=${DERIVED_DATA_PATH}/Build/Products/Release-iphonesimulator/Showtime.app" >>$GITHUB_ENV

      - name: Upload build to Waldo
        uses: waldoapp/gh-action-upload@v1
        with:
          build_path: ${{ env.APP_DIR_PATH }}
          upload_token: ${{ secrets.WALDO_UPLOAD_TOKEN }}
          is_debug_mode: true
