# This is a basic workflow to help you get started with Actions

name: Upload build to Waldo

defaults:
  run:
    working-directory: apps/expo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "staging" branch
  pull_request:
    branches: ["staging"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Expo prebuild
        run: STAGE=development yarn expo:prebuild

      - name: Build with Xcode
        run: |
          DERIVED_DATA_PATH=/tmp/Showtime-$(uuidgen)

          cd ios/ && xcodebuild -workspace Showtime.xcworkspace    \
                     -scheme Showtime                              \
                     -configuration Release                        \
                     -destination 'generic/platform=iOS Simulator' \
                     -derivedDataPath "$DERIVED_DATA_PATH"         \
                     clean build

          echo "APP_DIR_PATH=${DERIVED_DATA_PATH}/Build/Products/Release-iphonesimulator/Showtime.app" >>$GITHUB_ENV

      - name: Upload build to Waldo
        uses: waldoapp/gh-action-upload@v1
        with:
          build_path: ${{ env.APP_DIR_PATH }}
          upload_token: ${{ secrets.WALDO_UPLOAD_TOKEN_SIM }}
          is_debug_mode: true
